- README.md
cc @Carrotman42 
Hey Kevin,
I added some instructions on how to use your proxy with Kubernetes. The main difference is that k8s disallows using the metadata server for auth, so we have to create a secret and mount it as a volume.
I had one question about the proxy container though, do you publish that anywhere other than the gcr.io/google_appengine namespace? We probably shouldn't document that since the App Engine team might change the naming. If not, we can just document how to build your own container.
> Add instructions on how to use with Kubernetes.

- cmd/cloud_sql_proxy/cloud_sql_proxy.go
- cmd/cloud_sql_proxy/proxy.go
- cmd/cloud_sql_proxy/proxy_test.go
- proxy/fuse/fuse.go
- proxy/fuse/fuse_windows.go
Don't require -dir unless -fuse or -instances_metadata is used, or if
-instances contains a unix socket.
Don't allow -instances_metadata unless running on GCE.
Give a nicer error if windows users try to use -instances.
Give a nicer message for systems which don't support FUSE and forgot to
set -instances.
> Upgrade the logic for parsing flags and add test.

- cmd/cloud_sql_proxy/cloud_sql_proxy.go
- cmd/cloud_sql_proxy/proxy.go
Add a -projects flag which causes the proxy to open sockets for every
instance in the provided projects.
Also, if no other flags are provided and gcloud is on the PATH, then the
active project from that is used to find instances.
> Add -projects flag and autodetection of gcloud project

- cmd/cloud_sql_proxy/cloud_sql_proxy.go
- cmd/cloud_sql_proxy/proxy.go
- proxy/fuse/fuse.go
* Explicit message when a GCE VM doesn't have a service account attached.
* Message when FUSE exits.
* Don't print out a message when an ip version (ipv4/ipv6) isn't supported
Finishes up https://github.com/GoogleCloudPlatform/cloudsql-proxy/issues/11
> More log message cleanup:

- cmd/cloud_sql_proxy/cloud_sql_proxy.go
Add a short blurb explaining the proxy and some of the important flags, and then also do my own formatting of the flags so that the in-depth flag explanation looks consistent.
> Improve the --help text.

- README.md
- cmd/cloud_sql_proxy/cloud_sql_proxy.go
Replacing https://www.googleapis.com/auth/sqladmin with https://www.googleapis.com/auth/sqlservice.admin 
Fixing #20
> Correcting scope in permission check

- cmd/cloud_sql_proxy/cloud_sql_proxy.go
Correct the error message describing the use of the -credential_file
parameter. Previously it incorrectly suggested -credential**_s_**_file
> Fix typo in accountErrorSuffix

- cmd/cloud_sql_proxy/cloud_sql_proxy.go
Skip permissions check for GCE VM service account when a credential_file
or token were passed as arguments. Fixes #26
This was the least invasive change I could make to address this. The content check on tokenFile and token is now done here and in `authenticatedClient(ctx context.Context)` but I'm not sure what the best way to refactor this would be.
I tested on a default GCE instance and got the expected error when passing no credential file and successfully connected when passing the file.
> Respect credential_file and token args on GCE

- cmd/cloud_sql_proxy/proxy.go
Changing the listen call to use port 0 to grab an available port, the current code doesn't work on alpine linux in a container. This small change fixes it and I don't see a reason it would break other use cases assuming the Go source code is correct:
>If laddr has a port of 0, ListenTCP will choose an available port.
Example of this breaking:
>cloud_sql_proxy -dir=/cloudsql -instances=PROJECT:us-central1:INSTANCE=tcp:3306 -credential_file=/account.json
>2016/04/26 20:20:56 errors parsing config:
invalid "PROJECT:us-central1:INSTANCE=tcp:3306": unrecognized network tcp
> adding port 0 call to validNets listen test

- cmd/cloud_sql_proxy/build.sh
As requested in https://github.com/GoogleCloudPlatform/cloudsql-proxy/issues/28, work the logic for creating the docker container into the build script.
I could technically commit a standalone Dockerfile which does everything, but afaict the downside would be that the Go compiler and standard library would end up packaged together inside the container along with the proxy, making the distribution size pretty large. This way the container can be built from scratch, and can contain a single, statically-linked binary.
> Add support for building a docker container in build.sh

- CONTRIBUTORS
- README.md
- Only Second Generation is supported for CloudSQL Proxy
- On GCE you need to target `b.gcr.io/cloudsql-docker/gce-proxy:1.05` because of this Issue: GoogleCloudPlatform#35
> Update README.md for clearer instructions

- cmd/cloud_sql_proxy/cloud_sql_proxy.go
Will build fail when running 
```
go get github.com/GoogleCloudPlatform/cloudsql-proxy/cmd/cloud_sql_proxy
```
due to the changes to the Cloud packages, see the details in
https://godoc.org/google.golang.org/cloud/compute/metadata
> Fix undefined metadata due to changes to the Cloud packages

- README.md
The region part of the fully qualified instance parameter was missing: `project:region:name`.
Also, I removed the $ sign to avoid letting us think we can evaluate environment variable specified in command directly.
A workaround would be to wrap the command into `sh -c` but this docker image does not include any shell (`FROM scratch`).
cf. https://github.com/kubernetes/kubernetes/issues/1309#issuecomment-55524273
> Fix kubernetes usage example: missing region part. No environment variable

- cmd/cloud_sql_proxy/proxy.go
!os.IsNotExist(err) returns true even when err == nil.
> Bug fix: Create the directory first and then check using os.IsNotExist

- Kubernetes.md
- README.md
- cmd/cloud_sql_proxy/build.sh
Currently, one has to map a volume with certificates to the image.
We could simply fix that by using alpine and install certificates
directly in the image.
> Use alpine docker base image to get certificates

- tests/dialers_test.go
Expanded the dialer test to include being able to test using provided credentials as well as the default credentials. This should also provide a little bit more example code for people using the proxy in a go program without using default credentials
> Expanded the dialer test to provide additional examples of how to authenticate

- CONTRIBUTORS
- cmd/cloud_sql_proxy/cloud_sql_proxy.go
Hello,
This pull requests adds a `-quiet` flag. I am using `cloud_sql_proxy` in production on Google Container Engine, [per these instructions](https://cloud.google.com/sql/docs/postgres/connect-container-engine), and the constant "Connection established" logging pollutes our log streams (and will eventually incur additional costs to Stackdriver Logging). Please consider merging this PR so that we may silence logging.
Thanks!
> Add Quiet Flag

- cmd/cloud_sql_proxy/cloud_sql_proxy.go
- cmd/cloud_sql_proxy/proxy.go
- logging/logging.go
- proxy/certs/certs.go
- proxy/fuse/fuse.go
- proxy/proxy/client.go
- proxy/proxy/common.go
The flag defaults to true to keep old functionality (and to ease debugging when first setting it up), but people running the proxy in a server environment will likely want to turn off verbose output.
At some point we could consider setting the default to false.
Addresses #44 along with #100
> Add -verbose flag to allow users to turn off verbose output

- cmd/cloud_sql_proxy/cloud_sql_proxy.go
- proxy/proxy/client.go
- proxy/proxy/common.go
- proxy/proxy/dial.go
In the Client Proxy binary it is only used in FUSE mode, so only set it there. For most users this will change some O(n) operations to no-ops, which is nice.
> Remove the use of the ConnSet when it is not required.

- tests/gce_test.go
For reasons (I think) related to cached .a files on my computer, I was actually able to import a main package into other packages for a while. Either the .a files got cleaned or the recent Go compiler fixed the unintended support, but in any case now everyone can correctly run the gce_test.
> Fix gce_test.go to run on everyone's computer.

- cmd/cloud_sql_proxy/cloud_sql_proxy.go
- proxy/proxy/client.go
Fixes https://github.com/GoogleCloudPlatform/cloudsql-proxy/issues/99
> Add --refresh_config_throttle for setting the period between API calls.

- Kubernetes.md
Running the example yields this error:
```
Error from server (Invalid): error when creating "/dev/fd/63": DaemonSet.extensions "cloudsqlproxy" is invalid: spec.template.spec.containers[0].ports[0].name: Invalid value: "sqlproxy-port-database1": must be no more than 15 characters
Error from server (Invalid): error when creating "/dev/fd/63": Service "sqlproxy-service-database1" is invalid: spec.ports[0].targetPort: Invalid value: "sqlproxy-port-database1": must be no more than 15 characters
```
> Invalid Kubernetes config

- cmd/cloud_sql_proxy/cloud_sql_proxy.go
* s/UNIX/Unix/g
* s/gcloud/Google Cloud SDK/g
* s/\t/  /g
* Used an equal sign ('=') instead of a space when giving examples of parameters
* Documented the -verbose parameter in the 'General' section
* Documented the -instances_metadata parameter in the 'Connection' section
* Changed some references from 'flag' to 'parameter'
> Updates to the --help message.

- .gitignore
- cmd/cloud_sql_proxy/cloud_sql_proxy.go
- cmd/cloud_sql_proxy/proxy.go
- cmd/cloud_sql_proxy/proxy_test.go
- proxy/proxy/client.go
- proxy/proxy/client_test.go
- proxy/proxy/common_test.go
- tests/common.go
- tests/connection_limit_test.go
- tests/dialers_test.go
This is a first shot at trying to implement a hard limit on the number of connections to accept before refusing new connections to avoid OOM when memory resources are limited, as suggested by @Carrotman42 in #103.
TODO:
> Add -max_connections flag to put a hard limit on the number of connections

- README.md
- cmd/cloud_sql_proxy/cloud_sql_proxy.go
in spirit of keeping manifest files same across different projects,
it'd be good to pass some config options via environment variables.
with this change, one can pass either flag -instances or INSTANCES
environment variable to get same results
> cmd: use INSTANCES env var

- cmd/cloud_sql_proxy/proxy.go
- proxy/fuse/fuse.go
- proxy/proxy/client.go
This should prevent the Cloud SQL proxy from dying once it e.g. hits the
max filedescriptor limit.
> Gracefully handle Temporary errors from Accept()

- proxy/dialers/mysql/hook.go
The [go-sql-driver 1.4](https://github.com/go-sql-driver/mysql/blob/master/CHANGELOG.md#version-14-2018-06-03) release mentions the following change:
```
- Allow native password authentication by default (#644)
- NewConfig function which initializes a config with default values (#679)
```
The mysql.Config setting [AllowNativePasswords](https://github.com/go-sql-driver/mysql/blob/master/dsn.go#L55) should thus be default true, and it's correctly initialized when using the [NewConfig()](https://github.com/go-sql-driver/mysql/blob/master/dsn.go#L66) function. This cloudsql dialer code however currently does not use that constructor, instead it creates a *mysql.Config struct itself. This means `AllowNativePasswords` is uninitialized and false, which is not the correct default or expected …
> Use NewConfig() to initialize mysql.Config with correct defaults

- proxy/proxy/client.go
Use a custom peer certificate check to verify our non-standard certificates.
fixes #194
> Fix go 10.11 CN issue

- cmd/cloud_sql_proxy/cloud_sql_proxy.go
- cmd/cloud_sql_proxy/proxy.go
- proxy/proxy/dial.go
- proxy/util/gcloudutil.go
gcloud and application default credentials use different GCP projects for API quota purposes. Generally for development, or if customers want to use their own credentials for audit logging purposes, we want customers to use the auth token that is setup with `gcloud auth login`, and in particular we want to recommend that application default credentials be associated with service accounts as opposed to personal identities.
There are a couple of changes to how we detect and use the gcloud active project in this PR as well:
- Use LookupPath to determine if gcloud is not in the path instead of looking for an error message in the string
- Detect the case where gcloud is set up, but has no active project
- Add support for windows, where the gcloud command is `gcloud.cmd`
- Errors when invoking …
> Use gcloud oauth token before trying application default credentials

- cmd/cloud_sql_proxy/cloud_sql_proxy.go
This is for consistency with the jdbc socket factory.
> Flag ip_address_type references "public" instead of "primary"

- cmd/cloud_sql_proxy/cloud_sql_proxy.go
- logging/logging.go
Related issues: #106 #138 #149 
We noticed that debug messages from our Cloud SQL proxy would be considered as errors in stack driver since all log messages are sent to `stderr` as is defined by the default logger in the go log package: https://golang.org/src/log/log.go?#L73
This Pull requests sets up two new loggers, one for verbose / info messages which log to `stdout` and one for error messages which log to `stderr`.
I believe this should fix the problems as described in #138
> Stdout and Stderr Loggers

- proxy/util/gcloudutil.go
* Print out the error message from Gcloud when it can't print out its config
* Fix the error message printed out when reading config for reasons other than figuring out the gcloud project.
> Two fixes in GcloudConfig for usability

- cmd/cloud_sql_proxy/cloud_sql_proxy.go
For example, gcloud's credential files will have either type authorized_user or service_account. JWTConfigFromJSON only supports service accounts, while CredentialsFromJSON supports both service accounts and authorized users.
This was tested with a regular gmail account and a service account using the legacy JSON auth files created by gcloud in .config/gcloud/legacy_credentials/*/adc.json
> Support non-service-account credential files when run as a binary

- cmd/cloud_sql_proxy/cloud_sql_proxy.go
- proxy/proxy/client.go
- proxy/proxy/client_test.go
This PR supersedes #178 and takes in to account (most) of @hfwang's comments. By default, the proxy will automatically terminate when receiving a TERM signal (just like it currently does). People can also specify a timeout (`-term_timeout=30s`) to let the proxy wait for up to a certain amount of time before exiting.
If there are no active connections, the proxy will exit early (with a status code of 0). If it waits for the entire timeout period and there are still active connections, it will exit with a status code of 2. I picked 2 because I was seeing exit codes of 2 with the existing version but that could be because I have 2 open connections per proxy.
> Gracefully handle TERM signals

- proxy/dialers/postgres/hook.go
This lets tools such as https://github.com/luna-duclos/instrumentedsql wrap the driver and provide instrumentation.
> Publicly expose the driver so it can be wrapped

- cmd/cloud_sql_proxy/cloud_sql_proxy.go
- When running cloud_sql_proxy in GCE instance that is configured with gcloud, cloud_sql_proxy fails saying:
the default Compute Engine service account is not configured with sufficient permissions to access the Cloud SQL API from this VM. Please create a new VM with Cloud SQL access (scope) enabled under "Identity and API access". Alternatively, create a new "service account key" and specify it using the -credential_file parameter
This happens because the auth check function doesn't check if gcloud auth is available.
Fix: Add additional gcloud check before checking for GCE metadata scopes.
> Validate gcloud auth before checking GCE scope

- cmd/cloud_sql_proxy/cloud_sql_proxy.go
Hello
In situations when outgoing traffic comes through a firewall (or network policy) and there is no rule allowing to make HTTP requests to any IP, `cloud_sql_proxy` will wait on start 30 seconds before it starts to listen TCP socket and accept connections. These 30 seconds it's trying to GET `http://metadata.google.internal`. So you need to increase `initialDelaySeconds` for readiness and liveness probes for `cloud_sql_proxy` sidecar and main containers both. This increases deploy time, timeouts etc. 
I think we need to override default timeout and if GET request doesn't succeed in 2 seconds,the function `onGCE()` returns `false` and we continue boot process.
Another possible solution is to add logging of this error. I spent a few hours to understand why our cloud_sql_proxy start so …
> Don't wait as long when calling onGCE and metadata server is unavailable

- cmd/cloud_sql_proxy/cloud_sql_proxy.go
This changes it so the relative priority of token sources is:
--credential_file flag
GOOGLE_APPLICATION_CREDENTIALS environment variable
--token flag
gcloud auth
FindDefaultCredentials (see https://github.com/golang/oauth2/blob/28207608b83849a028d4f12e46533a6b6894ecaf/google/default.go#L61-L76)
The previous change had inserted gcloud auth before FindDefaultCredentials, which resulted in gcloud auth overriding GOOGLE_APPLICATION_CREDENTIALS. After this change, GOOGLE_APPLICATION_CREDENTIALS still overrides the --token, however documentation states that the environment variable and the flag are interchangeable and that seems to be the order people are expecting.
> Treat GOOGLE_APPLICATION_CREDENTIALS env the same as credential file flag

- Kubernetes.md
we found out that the cloudSQL proxy stops accepting new connections upon SIGTERM.
while the addition of `term_timeout` flag helps to terminate gracefully on existing connections, this becomes a problem when a dependent container (a web server, in most cases) connecting to the proxy requires new connections at that point.
our workaround was to make user of k8s's lifecycle hook (preStop) to delay the termination while the web server can finish up existing HTTP requests (which requires DB querying over connection pools).
I thought it may be useful to add some notes here about it 🙇
> docs: update k8s deployment sample to explain about graceful shutdown

- tests/common.go
This makes it easier to run the tests using our internal GCP project which has more restrictive firewall rules.
> Add a flag to control the network tags applied to the created test VM

- tests/common.go
Use debian-9 in tests, and add a flag that allows controlling whether the test VM has a public IP or not. If the instance does not have a public IP, then the private IP will be used when SSHing
> test VM uses debian-9 and add flag for public/private SSH

- cmd/cloud_sql_proxy/proxy.go
- proxy/certs/certs.go
First generation instances are not supported by the proxy, so this causes connections to them to fail slightly faster (otherwise we need to wait for the connection to timeout!)
> Proxy rejects requests for first generation instances.

- proxy/limits/limits.go
- proxy/limits/limits_freebsd.go
On FreeBSD, the type for rlimit.max & rlimit.cur are int64. Currently cloudsql-proxy expects them to be uint64. This pull request casts the type of rlimit.cur & rlimit max to uint64, & casts the value of the passed in`wantFDs` to int64 when trying to assign it to rlim.Cur & rlim.Max.
See https://github.com/perkeep/perkeep/issues/925 & https://camlistore-review.googlesource.com/c/camlistore/+/10147/ for other projects where this has reared its head.
> Fix issues with mismatched rlimit types on FreeBSD

- README.md
- proxy/README.md
Also add a clarifying comment about package stability and lack of guarantee.
> README: move dialer specific instructions to "proxy" subdirectory

- cmd/cloud_sql_proxy/cloud_sql_proxy.go
For the flag "host", the value should always end with '/'.
> Added the error handling of the incorrect host flag setting

- README.md
- cmd/cloud_sql_proxy/cloud_sql_proxy.go
- cmd/cloud_sql_proxy/proxy.go
- cmd/cloud_sql_proxy/proxy_test.go
Fork of #265, updated to include automatic addition of the suffix for Postgres instances.
> Set custom per instance socket address

- Dockerfile
> Add Dockerfile for building cloud-sql-proxy images. 

- Dockerfile
* Added feature to specify per instance custom socket path  (#289)
* Updated default dialer IP type to "PUBLIC,PRIVATE" (#294)
* Updated Dockerfile for building proxy images. (#296)
* Added gcr.io mirrors in other regions (`us`, `eu`, and `asia`) (#295)
* Add `InitWithClient` and deprecate `InitClient` to prevent a mutex copy. (#273)
> Release v1.15

- cmd/cloud_sql_proxy/proxy.go
Fixes #288 
This change causes the program to exit on error during initial startup. This will prevent the container from entering a bad state on startup after a failed authentication, network error etc.
> Bubble err up on fail to parse instance configs instead of ignoring

- cmd/cloud_sql_proxy/proxy.go
If an error is hit while parsing instance configurations, this error should bubble up.
Also, while watching instances, if the instance configs error, we should assume the instance list is bad, and not process the result.
> Return errors, and avoid bad updates

- Dockerfile
Set the version in the Dockerfile to `1.17-dev` for using the prerelease versions.
> Prepare for release v.1.17

- Dockerfile
Updates base image to `distroless/base-debian10:nonroot` and runs as a non root user.
Fixes #320.
> Improve Dockerfile security.

- proxy/proxy/client.go
> Fix typo in client.go

- cmd/cloud_sql_proxy/cloud_sql_proxy.go
- cmd/cloud_sql_proxy/proxy.go
Fixes #331.
Also address a couple of instances where the base url was not applied. 
Note: I considered updating from `New` to `NewClient` since the former is deprecated, but decided that it requires larger restructuring.
> fix: Remove incorrect api base url from the host flag.

- .gitignore
I've almost checked the binary a few times in; is there a reason we need to have this in the repo? 
Small change; can open an issue if there's enough of a reason to
> fix: Prevent the binary from getting checked in when using go build

- Dockerfile
* Updated base image for `gcr.io/cloudsql-docker` to `gcr.io/distroless/base-debian10:nonroot`
* Fix compatibility with `google.golang.org/api v0.15.0` or higher
* Added `-skip_failed_instance_config`: Setting this flag will allow you to prevent the proxy from terminating when some instance configurations could not be parsed and/or are unavailable.
* Update to dial database connections using [`proxy.FromEnvironment`](https://godoc.org/golang.org/x/net/http/httpproxy#FromEnvironment). This enables support for proxies such as SOCKS5.
> Release 1.17

- Dockerfile
* Updated base image for `gcr.io/cloudsql-docker` to `gcr.io/distroless/base-debian10:nonroot`
* Fix compatibility with `google.golang.org/api v0.15.0` or higher
* Added `-skip_failed_instance_config`: Setting this flag will allow you to prevent the proxy from terminating when some instance configurations could not be parsed and/or are unavailable.
* Update to dial database connections using [`proxy.FromEnvironment`](https://godoc.org/golang.org/x/net/http/httpproxy#FromEnvironment). This enables support for proxies such as SOCKS5.
> Release v1.17

- proxy/proxy/client.go
`time.Sleep(1)` is equivalent to `time.Sleep(time.Nanosecond)` (because `time.Nanosecond==1`*). I am only guessing that "1 second" was the intended sleep interval (though it seems appropriate). Feel free to suggest a different duration.
* https://golang.org/pkg/time/#Nanosecond
> Sleep more than a nanosecond during SIGTERM shutdown

- cmd/cloud_sql_proxy/cloud_sql_proxy.go
Before this change any error encountered during a forced shutdown via proxyClient.Shutdown will not be printed out, yet when there is an error the Proxy will still exit with a nonzero status. In addition to exiting with a nonzero status, this CL causes the errors to actually be printed out.
Note that log.Fatal(f) exits the program with exit code 1, which is a change from the prior implementation which exited with code 2. Let me know if exit code 2 was particularly important; I will happily log a message and explicitly exit(2).
I noticed this upon reading issue https://github.com/GoogleCloudPlatform/cloudsql-proxy/issues/388.
> Print out any errors during SIGTERM-caused shutdown

- proxy/proxy/client.go
Add a small optimization to better cap the max amount of time the proxy spends waiting for incoming connections to close. 
/cc @Carrotman42
> Optimize term-timeout wait.

- Dockerfile
- examples/kubernetes/README.md
- examples/kubernetes/no_proxy_private_ip.yaml
- examples/kubernetes/proxy_with_sa_key.yaml
- examples/kubernetes/proxy_with_workload_identity.yaml
Specify nonroot user by uid to work with runAsNonRoot.
I've backported this fix to release v1.17 since it should be fully compatible. I will update the container tags once this is merged. 
- Fixes #386
> fix(container): Specify nonroot user by uid to work with runAsNonRoot.

- README.md
💁 The previous repository was deprecated in favour of https://github.com/rimusz/charts some time ago. See https://github.com/helm/charts/pull/9219 for further context and information.
> Update Helm chart URL

- cmd/cloud_sql_proxy/cloud_sql_proxy.go
Updates the format of the userAgent string returned by the userAgentFromVersionString function.
An example of the new format returned is "cloud_sql_proxy/1.16"
- Fixes #398
> Update format of userAgent string

- README.md
Updated documentation for proxy container images in README.md
- Fixes #418
> chore(docs): Remove "v" from container image tags

- README.md
Update `go get` installation command with `GO111MODULE=on` in README.md.
- Fixes https://github.com/GoogleCloudPlatform/cloudsql-proxy/issues/421
> docs: Update go get command with GO111MODULE=on

- cmd/cloud_sql_proxy/cloud_sql_proxy.go
- proxy/certs/certs.go
- proxy/fuse/fuse.go
- proxy/fuse/fuse_test.go
- proxy/proxy/client.go
- proxy/proxy/client_test.go
Fixes #207
PostgreSQL requires that the Unix domain socket be named ".s.PGSQL.5432". This logic is already present when using the `-instances` or `-projects` flags; however, it does not work when the proxy is running with `-fuse`.
With this change, I am now able to run CloudSQL proxy with `-fuse` and use `psql` to connect to the database:
```
$ INSTANCE=<project:location:name>
$ cloudsqlproxy -fuse -dir /tmp/fuse/cloudsql -fuse_tmp /tmp/fuse/tmp &
$ psql -h /tmp/fuse/cloudsql/$INSTANCE
Password:
```
To eliminate multiple instance.get calls, the implementation reuses the instance cache in the proxy client to also store database version. This is then used in` fuse.go` to create the appropriate directory structure. To accommodate this change, the fuse instance now takes a client pointer …
> fix: Add socket suffix for Postgres instances when running in `-fuse` mode

- README.md
The PR addresses the missing documentation issue while configuring cloud_sql_proxy.
Adding documentation for the flag log_debug_std
- Fixes #428
> docs: add documentation for log_debug_std flag

- renovate.json
renovate-bot PRs should run `go mod tidy`
> chore: add goModTidy to renovate config

- .build/gcs_upload.yaml
- Dockerfile
- Dockerfile.alpine
- Dockerfile.buster
- cmd/cloud_sql_proxy/cloud_sql_proxy.go
Adds support for semantic-version style metadata (`$version-prelease+metadata1.metadata2`) in version tags and fixes user agent to work with the new version format.
> chore: Add support for metadata to version strings

- .github/workflows/update-versions.yml
- Dockerfile
- Dockerfile.alpine
- Dockerfile.buster
This GitHub Actions workflow checks out the source branch of any PR generated by `release-please[bot]` and pushes another commit to update the version string in the proxy. It *should* push the commit as release-please bot and get past CLA issues that way
> chore: Add a workflow to update the versionString on release PRs

- .github/workflows/update-versions.yml
The action isn't triggering and I suspect it's because of these missing quotes.
> chore: fix branch name on update-version workflow

- Dockerfile.alpine
- Dockerfile.buster
Enabled the "user_allow_other" option in `/etc/fuse.conf`. This allows non-root users to mount fuse filesystems, which allows fuse mode to work when deployed to k8s. 
- Fixes #444
> fix(containers): Allow non-root users to mount fuse filesystems for alpine and buster images

- cmd/cloud_sql_proxy/cloud_sql_proxy.go
- cmd/cloud_sql_proxy/proxy.go
- proxy/certs/certs.go
Update the SQLAdmin API calls to use an instance name with a region prefix with the format <region>~<instance-name> to prevent issues with conflicting instance names when sqladmin v1 is released and instance names become regionally unique instead of globally unique
> feat: use regionalized instance ids to prevent global conflicts with sqladmin v1

- .build/gcs_upload.yaml
A few of our metadata strings for compiled proxies were using "binary" as a modifier. I removed that to make them all consistent.
> chore(releasing): Remove 'binary' from several metadata strings

- proxy/proxy/client.go
- proxy/proxy/client_test.go
Moves the `Client.ConnectionsCounter`  field to the start of the struct since these values are guaranteed to be 64-bit aligned. Also adds a regression test to ensure that it doesn't get moved out of alignment in the future. 
- Fixes #543
> fix: Ensure neccesary fields are 64-bit aligned

- README.md
- cmd/cloud_sql_proxy/cloud_sql_proxy.go
- proxy/certs/certs.go
- proxy/proxy/client.go
- proxy/proxy/client_test.go
- tests/postgres_test.go
This PR introduces the client side changes needed for utilizing the access token for cloudsql proxy IAM database authentication. The feature is gated by newly introduced flag `--enable_iam_login`. When enabled it includes the access token in the `sqladmin.SslCertsCreateEphemeralRequest` and send the request to create a ephemeral cert with access token info in it, which will later be used to perform IAM authentication. The access token has TTL of 1 hour and the ssl cert will be refreshed whenever access token expires or cert expires.
> feat: Added '-enable_iam_login' flag for IAM db authentication

- .github/renovate.json
See https://github.com/renovatebot/renovate/blob/master/docs/usage/semantic-commits.md#changing-the-semantic-commit-type.
> chore: renovate bot uses chore for all commits

- .kokoro/release_artifacts.sh
When running the `sha256sum --binary` command with input from standard
in, the output is:
$SHA_HERE *-
As noted in the man page for sha256sum, the asterix indicates "binary
mode." The trailing dash means standard in.
This commit removes the extraneous information such that only the SHA
will be printed in the final output.
See https://unix.stackexchange.com/questions/487028/print-sha-sums-without-at-the-end
for more.
> chore: print sha256sum only in release script

- .build/gcs_upload.yaml
Added steps to compile binaries for Linux/ARM32 and Linux/ARM64, as well as Darwin/ARM64. The Linux versions have been tested with QEMU, but not on an actual ARM machine yet. 
Not sure how to test the Darwin one (for M1 Macs), although it's probably low priority, since Apple says that [the new Macs have Rosetta to run programs compiled for AMD64](https://support.apple.com/en-us/HT211861). 
> feat: add ARM releases

- .build/gcs_upload.yaml
A previous commit had set a Darwin build to 32-bit Linux.
> chore: Correct build configuration

- proxy/certs/certs.go
- proxy/proxy/client.go
- tests/postgres_test.go
Updates `TokenExpiration()` to return a zero value if TokenSource is unset.
- Fixes #640
> fix: verify TokenSource exists in TokenExpiration()

- .envrc.example
- CONTRIBUTING.md
- README.md
- cmd/cloud_sql_proxy/cloud_sql_proxy.go
- proxy/README.md
This commit cleans up the project README and consolidates all additional
documentation into the docs folder.
Fixes #362.
Fixes #599.
Fixes #498.
Fixes #401.
> chore: update README

- .gitignore
- proxy/certs/certs.go
- proxy/proxy/client.go
- proxy/proxy/client_test.go
- proxy/util/gcloudutil.go
When clients use IAM authorization, an OAuth2 token is inserted into the
local certificate. In a previous commit, that token could expire within
the configured buffer (i.e., 5 minutes), causing the proxy to fail to
refresh its configuration and to report that the "new ephemeral
certificate expires too soon." Because the code always checked the token
expiration and the certificate expiration, this bug would affect both
clients using IAM auth and clients *not* using it.
This commit ensures the token's expiration is only considered when IAM
auth has been enabled, and when it has been enabled, this commit
likewise ensures the token's expiration is well beyond the buffer.
Fixes #643.
> fix: use new oauth2 token with cert refresh

- go.mod
- go.sum
- proxy/util/gcloudutil.go
See https://blog.golang.org/path-security for details.
> fix: prevent untrusted gcloud exe's from running

- .envrc.example
- tests/postgres_test.go
Also, add the associated environment variable to .envrc.example.
> chore: ensure IAM user is present before test run

- proxy/util/gcloudutil.go
Reverts behavior to verify a gcloud token is available before using it as a TokenSource, and caches the token when possible.
- Fixes #655
> fix: perform initial gcloud check and reuse token

- proxy/certs/certs.go
- proxy/proxy/client.go
- proxy/proxy/client_test.go
This commit is a follow-on to #648 which only partially addressed the
issue reported in #643. In a previous commit, we ensured the associated
OAuth2 token was refreshed before requesting an ephemeral certificate.
However, the oauth2.TokenSource stored in certs.RemoteCertSource would
nonetheless report an unrefreshed token's expiration. As a result,
attempts to refresh the configuration would fail given the unrefreshed
token would expire too soon.
This commit takes a new approach by updating the leaf certificate's
expiration to be the earlier of the ephemeral certificate's expiration
or the token's expiration. It likewise removes any checks of the token's
expiration outside of certs.RemoteCertSource.
Fixes #643.
> fix: ensure certificate expiration is correct

- .build/gcs_upload.yaml
- .gitignore
- Increase build timeout to 15 minutes now that we have more images to build
- Ensure gitignore strictly defines what to ignore so that Cloud Build doesn't fail to copy parts of our code tree.
> chore: ensure build process has enough time and all the code

- proxy/proxy/client.go
Changes `refreshCfg` to update the `lastRefreshed` field of of the cached result once the decision to make a refresh has been made and before the cache lock is released. This fixes a race condition where more than one goroutine could attempt to perform a refresh. 
- Fixes #427
> fix: prevent refreshCfg from scheduling multiple refreshes

- cmd/cloud_sql_proxy/cloud_sql_proxy.go
- proxy/proxy/client.go
With IAM login enabled, the proxy would fail to refresh its certificate
when using Application Default Credentials retrieved from the metadata
server. The metadata server returns an access token that is refreshed
only when the expiration is within ~60 seconds. As a result, when the
proxy attempted a refresh of the certificate, it would fail because the
token did not have enough time left on it relative to the default buffer
(i.e., 5 minutes).
This commit configures the buffer to 55 seconds when IAM login is
enabled. When a token has ~60 seconds before expiration, the refresh
logic will schedule a refresh 5 seconds in the future. When 5 seconds
have elapsed, the refresh logic will get a new token whose expiration is
in an hour and restart the clock on the next refresh.
Fixes #662.
> fix: lower refresh buffer and config throttle when IAM authn is enabled

- proxy/README.md
The links for the examples were broken, I changed their target path to up-to-date one.
> fix: Update Go Cloud SQL proxy dialer example usage links

- proxy/fuse/fuse.go
- proxy/proxy/client.go
- proxy/proxy/client_test.go
Expands on the behavior introduced in #666 by reconfiguring the `cachedCfg` function to prevent multiple simultaneous refreshes from occurring at once. 
- Fixes #427
> fix: fix cache to prevent multiple concurrent refreshes

- cmd/cloud_sql_proxy/cloud_sql_proxy.go
- logging/logging.go
Fix the combined use of structured logs (`-structured_logs`) and standard output debug logs (`-log_debug_stdout`).
- Fixes #725
> fix: Allow combined use of structured logs and -log_debug_stdout

- cmd/cloud_sql_proxy/cloud_sql_proxy.go
- logging/logging.go
Previously, when structured logging was enabled, the code would ignore
the value of the verbose flag. This commit ensures the verbose flag
works with structured logging.
Fixes #727.
> fix: structured logging respects the -verbose flag

- examples/kubernetes/README.md
- examples/kubernetes/proxy_with_sa_key.yaml
- examples/kubernetes/proxy_with_workload_identity.yaml
> chore: include example resource requests

- .github/renovate.json
See https://github.com/renovatebot/renovate/issues/6213#issuecomment-816600594 for context.
Also, note: https://github.com/renovatebot/renovate/issues/6213#issuecomment-836869203.
> chore: update renovate.json to always use Go 1.16

- proxy/certs/certs.go
Strips trailing . characters from access tokens
- fixes #852
> fix: strip padding from access tokens if present

- .kokoro/tag_latest.sh
This script saves a person from having to click through the container
registry UI.
> chore: add script for tagging latest version

- README.md
- logging/logging.go
This fix will generate log messages as json documents that are compatible with [Google Cloud Logging](https://cloud.google.com/logging/docs/structured-logging#special-payload-fields). This fix ensure that Google Cloud Logging will pick up the severity and text message, even if the log is written on stderr.
There was no test for EnableStructuredLogs() and it is hard to create one. So I left it this way. I did test the flag manually. Given the complexity of the change, I hope this is ok.
- Fixes #860
> fix: use Google Cloud structured log format

- proxy/proxy/client_test.go
Renames TestValidate to TestParseInstanceConnectionName; removes wantValid from the table definition.
> fix: refactor client test

- proxy/fuse/fuse_test.go
The fuse tests were unreliable for two reasons:
1. All tests used the same two directories to mount and unmount FUSE file systems, and
2. The FUSE mount takes some amount of time, so promptly trying to close the connection was subject to race conditions.
This PR addresses both issues:
1. It uses distinct directories for each test, and
2. It attempts to close the connection at most 10 times before failing.
I've manually run the tests 15 times to verify (at least by best effort) that this fix does in fact work.
Fixes #856
> chore: make fuse tests reliable

- .kokoro/go116/macos/common.cfg
- .kokoro/go116/macos/continuous.cfg
- .kokoro/go116/macos/periodic.cfg
- .kokoro/go116/macos/presubmit.cfg
This is the first step in removing the macOS build for Go 1.14.
> chore: add macOS build for Go 1.16

- proxy/fuse/fuse.go
- proxy/fuse/fuse_darwin.go
- proxy/fuse/fuse_linux.go
- proxy/fuse/fuse_linux_test.go
- proxy/fuse/fuse_test.go
This commit addresses a longstanding [TODO](https://github.com/GoogleCloudPlatform/cloudsql-proxy/blob/b0184c4b9823bbf70249f92410b5e37cca729359/proxy/fuse/fuse.go#L56) and is related to https://github.com/GoogleCloudPlatform/cloudsql-proxy/pull/953.
Fixes #994.
> feat: verify FUSE is installed on macOS / linux

- CONTRIBUTING.md
This is probably the preferred option for macOS 12.0 and M1 chips. 
I noticed that the kokoro build is also installing `osxfuse`, but am unaware of what version of macOS it might be using (not a Googler).
> docs: suggest macfuse over osxfuse

- cmd/cloud_sql_proxy/proxy_test.go
- proxy/fuse/fuse_linux_test.go
- proxy/fuse/fuse_test.go
Allows the skipping of all fuse related tests with the short command, provided by go test.
Other package managers (nix, brew, etc) may want to build and test `cloud_sql_proxy` themselves. The fuse tests require external binaries with hardcoded paths in order to run. This is currently unworkable in nixpkgs.
- Fixes #<issue_number_goes_here>
> chore: skip fuse tests with `go test -short`

- .github/renovate.json
A recent commit in x/net introduced a breaking change for Go 1.14 and
before. Until we stop supporting Go 1.14, we'll need to pin to our
current version of x/net.
See
https://github.com/GoogleCloudPlatform/cloudsql-proxy/pull/1015 for
additional details.
> chore: ignore golang.org/x/net

- proxy/certs/certs.go
- proxy/certs/certs_test.go
Now when a SQL Admin API requests fails, we'll supply a read time set to
30 seconds before the present time to alleviate failures.
Fixes #977.
> feat: add support for ReadTime in Admin API requests

- cmd/cloud_sql_proxy/cloud_sql_proxy.go
This commit adds a CLI flag quota_project such that users may provide a
project against which the SQL Admin API quota is calculated. Typically,
this flag will be used for internal development purposes.
Note: there is an API option WithQuotaProject that does the same thing.
However, that option is not compatible with WithHTTPClient and so we
manually add the quota project instead.
> feat: add support for specifying a quota project

- cmd/proxy.go
Update it so we're using `cmd.Print...` everywhere over `log.Print...`, and cleaning up some roughly related cleanup.
> fix: improve logging and cleanup

- proxy/proxy/client.go
- proxy/proxy/client_test.go
- proxy/proxy/connect_tls_117.go
- proxy/proxy/connect_tls_other.go
When a TLS handshake fails, the client would invalidate the
configuration without recording the associated error. When the liveness
check runs, it would panic when trying to print the invalidated
configuration's error because the error was nil. This commit ensures
that when the proxy invalidates a configuration, it includes the error.
Fixes #1065.
> fix: invalidated config should retain error

- README.md
Latest Go versions use "go install" instead of "go get".
> docs: update the install from source instructions

- README.md
Alternative to https://github.com/GoogleCloudPlatform/cloudsql-proxy/pull/1104
> feat: add Go version support policy

- cmd/proxy.go
When lauching the proxy with multiple instances, a second goroutine
would attempt to send on a closed channel. This commit resolves the
problem by leaving the channel open and preventing a goroutine leak by
attempting a best effort send.
> fix: don't send on a closed channel

- .build/alpine.yaml
- .build/buster.yaml
- .build/default.yaml
- Dockerfile
- Dockerfile.alpine
- Dockerfile.buster
Enable multiarchitecture builds in Cloud Build to make our Docker images compatible with ARM64 Linux and MacOS.
> feat: make Docker images ARM-friendly

- proxy/proxy/client.go
Log the time duration for re-scheduling the refresh of ephemeral certificate rounded to milliseconds.
Right now, logging the current left duration for refresh is quite verbose. For instance, the message I see logged on my console why I try to connect to one instance is: `Scheduling refresh of ephemeral certificate in 54m59.294191713s`. I feel that this contains a little bit too much details. Rounding the timeToRefresh value during logging to ensure per-millisecond granularity should be good enough.
> chore: round timeToRefresh for logging.

- proxy/proxy/client.go
Removing the monotonic clock reading ensures the code is resilient when
waking from sleep (where the monotonic clock may be inaccurate for some
time).
Fixes #1199.
> fix: strip monotonic clock reading during refresh

- tests/alldb_test.go
- tests/healthcheck_test.go
Skipping `TestMultiInstanceDial` as it seems to have become flaky now that tests are running on Github Actions.
Created #1228 for re-enabling and fixing test.
> chore: skip TestMultiInstanceDial test

- .github/workflows/lint.yaml
Enabling lint job to be triggered by `tests: run` label on PRs.
> chore(ci): add label trigger to lint action

- .github/trusted-contribution.yml
Now that kokoro builds have been removed there is no need for the `kokoro:force-run` label to be auto-applied by the [trusted-contribution](https://github.com/googleapis/repo-automation-bots/tree/main/packages/trusted-contribution) bot on PRs.
Instead PRs from `renovate-bot` etc. should apply `tests: run` label instead.
> chore(ci): apply "tests: run" to trusted contributors

- .github/workflows/v2-periodic.yaml
Allowing v2 branch to use Github Actions for tests.
Need new file `v2-periodic.yaml` because `schedule` event by default is only configurable on default branch (main). So need explicit new schedule action to checkout v2 branch and run tests.
> chore(ci): enable Github Actions tests on v2

- README.md
Updating CI badge in README to track and link tests of latest commit on `main` branch.
Example of working badge: [README](https://github.com/GoogleCloudPlatform/cloudsql-proxy/blob/update-badge/README.md)
> chore: link CI badge to tests action

- cmd/root.go
- cmd/root_test.go
- internal/proxy/proxy.go
- internal/proxy/proxy_test.go
This consolidates all code relating to cloud.google.com/go/cloudsqlconn into the internal/proxy package.
> chore: Move dialer options out of cmd/main.go and into internal/proxy.go

- cmd/root.go
- cmd/root_test.go
- internal/proxy/proxy.go
Specifies an alternate api endpoint to use for calling the cloud sql admin 
api instead of https://sqladmin.googleapis.com/. This replaces the
This new flag replaces the -host flag in cloudsql-proxy V1.
> feat: add --sqladmin-api-endpoint flag for specifying sqladmin api endpoint

- cmd/root.go
- cmd/root_test.go
- internal/proxy/proxy.go
- internal/proxy/proxy_test.go
Previously, when a caller would try to close the client that was
serving, there was a data race between the assignment of a listener, and
the removal of the listener within socketMount. This commit ensures that
the listener is created prior to the socket mount and so makes the data
race impossible.
> fix: resolve data race on closing client

- cmd/root.go
- cmd/root_test.go
- internal/proxy/proxy.go
- internal/proxy/proxy_test.go
This is the v2 version of term_timeout and will make proxy wait at most
for the specified duration beforing existing once a SIGTERM has been
received by the process.
> feat: add max-sigterm-delay flag

- internal/proxy/proxy_test.go
> chore: increase wait time to ensure TCP connections

- Dockerfile
- Dockerfile.alpine
- Dockerfile.buster
> fix: add entrypoint to Dockerfiles

- internal/proxy/proxy_test.go
This commit updates a test to check all connections for an io.EOF error.
Fixes #1309.
> chore: check all connections for io.EOF

- internal/proxy/fuse.go
- internal/proxy/fuse_test.go
- internal/proxy/proxy.go
- internal/proxy/proxy_test.go
This commit also ensures that closing the proxy.Client blocks until all
listeners are closed.
> feat: add support for FUSE connections

- .github/release-please.yml
Apply explicit configuration to the v1 branch so that it uses 'simple' strategy and 'CHANGELOG.md' for changes.
> chore: adjust release-please configuration to properly handle v1

- internal/proxy/fuse.go
- internal/proxy/fuse_test.go
- internal/proxy/proxy.go
- internal/proxy/proxy_other.go
- internal/proxy/proxy_windows.go
> fix: don't build FUSE paths for Windows

- .github/workflows/tests.yaml
- .github/workflows/v1-periodic.yaml
By explicitly configuring `shell: bash` in test step it enables `set -eo pipefail` ([documentation](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#exit-codes-and-error-action-preference)) which means errors in left side of pipe will no longer be suppressed by the success of the right side of the pipe.
```yaml
go test -race -v ./... | tee test_results.txt
```
Additionally, with new `pipefail` being set, if line that runs the test `go test -race -v ./... | tee test_results.txt` fails (i.e. a test fails) than this causes an exit code and for the line below it `go-junit-report ...` not to be run which in turn disables flakybot from working as it requires XML sponge log.
By moving the convert XML functionality to its own step in the workflow we can make …
> chore: fix piped test errors being suppressed

- internal/proxy/proxy.go
- internal/proxy/proxy_other_test.go
- internal/proxy/proxy_test.go
- internal/proxy/proxy_windows_test.go
> fix: set write permissions for group and other

- .github/renovate.json
Also, remove unused v1 rules, since renovate doesn't run against multiple branches.
> chore: limit max concurrent PRs

- cmd/root.go
- cmd/root_test.go
- go.mod
- go.sum
- internal/proxy/proxy.go
- tests/connection_test.go
- tests/mysql_test.go
- tests/postgres_test.go
- tests/sqlserver_test.go
> feat: add support for credentials JSON flag

- .github/workflows/tests.yaml
- internal/proxy/fuse.go
- internal/proxy/fuse_freebsd.go
- internal/proxy/fuse_openbsd.go
- internal/proxy/proxy_other.go
- internal/proxy/unix.go
> fix: restore openbsd and freebsd support

- .envrc.example
- .github/workflows/tests.yaml
- README.md
- cmd/root.go
- cmd/root_test.go
- internal/proxy/proxy.go
- tests/common_test.go
- tests/connection_test.go
- tests/mysql_test.go
- tests/postgres_test.go
- tests/sqlserver_test.go
Note: the CLI flag matches the gcloud UI.
Fixes #417
> feat: add support for impersonation

- .build/gcs_upload.yaml
Currently, the job takes ~18min
> chore: bump Cloud Build timeout

- README.md
- cmd/root.go
- cmd/root_test.go
- go.mod
- go.sum
> feat: configure the proxy with environment variables

- cmd/errors.go
- cmd/root.go
SIGTERM (15) is 128+15=143 (not 137).
See https://tldp.org/LDP/abs/html/exitcodes.html and https://komodor.com/learn/exit-codes-in-containers-and-kubernetes-the-complete-guide/ for details.
Fixes #1529.
> fix: return correct exit code on SIGTERM

- .build/bullseye.yaml
Restoring this is tracked in #1508.
> chore: disable arm64 build for bullseye

- README.md
- cmd/root.go
- examples/k8s-health-check/README.md
- examples/k8s-health-check/proxy_with_http_health_check.yaml
Fixes #1555
Fixes #1493
Fixes #1369
> docs: clean up health check docs

- README.md
Moves the credential section higher in the README - it's a prerequisite to being able to use the proxy.
> docs: move Credentials section higher in the README

- cmd/root.go
- cmd/root_test.go
- internal/proxy/proxy.go
- internal/proxy/proxy_test.go
This adds a new parameter `unix-socket-path` to instances to specify the precise unix socket path. 
For example, this command line: 
```
$ cloud-sql-proxy my-project:region:mydb?unix-socket-path=/var/cloudsql/mydb 
```
Will open a unix socket to the database at the path `/var/cloudsql/mydb`.
This is different than the existing parameter `unix-socket` which automatically appends the instance name to the path. 
- Fixes #1573
> feat: Add unix-socket-path to instance command arguments.

- cmd/root.go
- cmd/root_test.go
- internal/proxy/proxy.go
When a caller passes the --token flag with --auto-iam-authn, the Proxy will now require a separate --login-token. This changes ensures a token with SQL Admin scope does not make its way into the ephemeral certificate. Instead, the value passed to --login-token will be used and should have only the sqlservice.login scope.
> fix: ensure separate token source with auto-iam-authn

- cmd/cloud_sql_proxy/cloud_sql_proxy.go
- cmd/cloud_sql_proxy/cloud_sql_proxy_test.go
When token and enable_iam_login are provided,
the caller must also provide a login token to
ensure only a minimally scoped token in embedded
into the ephemeral certificate.
> fix: require login_token with token and enable_iam_login

- examples/k8s-health-check/proxy_with_http_health_check.yaml
- examples/k8s-service/pgbouncer_deployment.yaml
- examples/k8s-sidecar/proxy_with_sa_key.yaml
- examples/k8s-sidecar/proxy_with_workload_identity.yaml
Updating examples to point at latest version of the v2 proxy
> chore: update examples proxy version to v2.1.0

- Dockerfile.alpine
- Dockerfile.bullseye
- Dockerfile.buster
Dockerfiles should set `CGO_ENABLED=0` to statically link binaries, without it binaries are dynamically linked. This causes specific issues for alpine build as we were using the basic `golang:1.X` docker image to build the binary which is a debian image. Updating the alpine build to use `golang:1.X-alpine` for its build step.
Fixes #1678
> fix: build statically linked binaries

- examples/k8s-health-check/README.md
- examples/k8s-health-check/proxy_with_http_health_check.yaml
Hi,
I'm not sure if it's a typo but the `=` is needed in my case and used on [the other key/value args](https://github.com/GoogleCloudPlatform/cloud-sql-proxy/blob/v2.1.1/examples/k8s-health-check/README.md?plain=1#L100).
> docs: fix typo in k8s-health-check example

- .github/workflows/coverage.yaml
- .github/workflows/labels.yaml
- .github/workflows/lint.yaml
- .github/workflows/tests.yaml
- .github/workflows/v1-periodic.yaml
Take care of `Pinned-Dependencies` and `Token-Permissions` alerts
> ci: make workflows read-only and pin shas

- cmd/root.go
- internal/log/log.go
Add ability for `--structured-logs` and `--quiet` Proxy flags to be used together.
Fixes #1738
> fix: allow `--structured-logs` and `--quiet` flags together

- examples/k8s-health-check/README.md
- examples/k8s-health-check/proxy_with_http_health_check.yaml
This reorganizes and adds explanation to the startup and readiness probes. 
Also, this updates our recommendation to only use a startup and liveness probe, but not a readiness probe under most circumstances. 
Fixes #1757
> doc: Improve examples for k8s readiness probes.

- cmd/root.go
- cmd/root_test.go
This combination is insecure because it puts an OAuth2 token with broader scoped access than necessary into the ephemeral certificate.
Because gcloud-auth is a legacy flag, it is generally discouraged. This commit also adds a note to make that clear and provides a clear alternative using Application Default Credentials.
Fixes #1754
> fix: disallow auto-iam-authn with gcloud-auth

- internal/proxy/proxy.go
When the proxy starts its shut down, it will now accept additional connections when the max-sigterm-delay flag is passed. As before, if any connections are still open after the delay has elapsed, the Proxy will report an error.
Fixes #1640.
> feat: allow connections during shutdown

- main_windows.go
When the Windows service stops, it immediately spawns a command line instance with the same arguments. This rebinds to the same port(s) and effectively prevents the service from stopping or restarting.
> fix: Windows service stop

- README.md
This PR contains no functional changes, just fixing a few misspellings within `README.md`
> chore: README typo fixes

- cmd/root.go
Print shutdown message instead of error for the zero on sigterm case. 
Fixes #1885
> fix: remove the error message for zero on sigterm

- .github/renovate.json
@enocom let's add this back in to not overcrowd open PRs with renovate and to avoid X builds running at the same time.
> chore: limit concurrent renovate PRs

- .build/release_artifacts.sh
Adding additional tags to docker images.
Currently we only tag builds with a single tag such as `1.33.9-alpine`
This PR will result in additional tags such as `alpine`, `1.33-alpine`, and `1-alpine`.
The benefit is users who want to always pull the latest alpine build of the Proxy can now just pull the alpine tag etc.
Part of https://github.com/GoogleCloudPlatform/cloud-sql-proxy/issues/1820
> build: add shared tags to v1 docker images

- .build/release_artifacts.sh
Now that bullseye v1 build is working again we can re-add tags
> chore: re-add bullseye tags

- examples/k8s-sidecar/job_with_shutdown_hook.yaml
This example demonstrates how to use the /quitquitquit endpoint in a kubernetes job to allow job pods
to exit successfully when the main application container exits.
Fixes #1941
> docs: Add kubernetes job example

- internal/proxy/proxy.go
- internal/proxy/proxy_test.go
Let proxy continue to run even instances specified are inactive.
Tested these scenarios:
- inactive instances without TCP or Unix socket options
- inactive instances with TCP port
- inactive instances with Unix socket
> chore: improve logging with additional test coverage

- examples/k8s-health-check/README.md
- examples/k8s-health-check/proxy_with_http_health_check.yaml
The configuration example for health checks now matches match the default configuration used by the [cloud-sql-proxy-operator](https://github.com/GoogleCloudPlatform/cloud-sql-proxy-operator). 
Fixes #1943
> docs: Update the example healthcheck config 

- .github/workflows/coverage.yaml
- .github/workflows/lint.yaml
- .github/workflows/tests.yaml
This matches https://github.com/googleapis/google-cloud-go#go-versions-supported
> fix: update supported Go versions

- internal/proxy/proxy.go
Now, we use cloud-sql-proxy, and encounter an error as follows.
```
[{my-instance-name}] connection aborted - error writing to client: <nil>
```
we checked code, and noticed that nil error instance was used for logging.
> fix: use proper error instance to write error log

- cmd/root.go
- cmd/wait_test.go
To help ensure the Proxy is up and ready, this commit adds a wait command with an optional `--max` flag to set the maximum time to wait.
By default when invoking this command:
```
./cloud-sql-proxy wait
```
The Proxy will wait up to the maximum time for the /startup endpoint to respond. This command requires that the Proxy be started in another process with the HTTP health check enabled. If an alternate health check port or address is used, as in:
```
./cloud-sql-proxy <INSTANCE_CONNECTION_NAME> \
--http-address 0.0.0.0 \
--http-port 9191
```
Then the wait command must also be told to use the same custom values:
```
./cloud-sql-proxy wait \
--http-address 0.0.0.0 \
--http-port 9191
```
By default the wait command will wait 30 seconds. To alter this value, use:
```
./cloud-sql-proxy wait …
```
> feat: add support for wait command

- Dockerfile
- Dockerfile.alpine
- Dockerfile.bullseye
- Dockerfile.buster
Currently, the `cloud-sql-proxy` Dockerfiles that are built and published on GCR do not have any `LABEL` statements. In my use case of the `cloud-sql-proxy` image, I want to pin the image to a specific version and use GitHub Dependabot to periodically update the image to the latest version. Dependabot currently cannot check for updates to the `cloud-sql-proxy` image because it does not have the `org.opencontainers.image.source` label.
This commit adds the line
```dockerfile
LABEL org.opencontainers.image.source="https://github.com/GoogleCloudPlatform/cloud-sql-proxy"
```
to the Dockerfiles that specify the image contents in the `cloud-sql-proxy` repository. This has the effect of allowing Dependabot to track updates to this image as documented …
> chore: `LABEL` Dockerfiles with URL of source repo

- Dockerfile.alpine
This alpine image version does not have CVE-2023-5363, CVE-2023-5678 vulnerabilities
Related issue https://github.com/GoogleCloudPlatform/cloud-sql-proxy/issues/2048
> deps: update alpine image version to 3.18.5

- README.md
- examples/k8s-health-check/README.md
- examples/k8s-health-check/proxy_with_http_health_check.yaml
- examples/k8s-service/README.md
- examples/k8s-service/pgbouncer_deployment.yaml
- examples/k8s-sidecar/README.md
- examples/k8s-sidecar/job_with_shutdown_hook.yaml
- examples/k8s-sidecar/proxy_with_sa_key.yaml
- examples/k8s-sidecar/proxy_with_workload_identity.yaml
These examples are rendered into the official Google Cloud docs in certain code samples. Best to showcase our latest version if users decide to copy and paste without updating the version to latest.
> chore: bump Proxy container examples to v2.8.0

- Dockerfile
- Dockerfile.alpine
- Dockerfile.bullseye
- Dockerfile.buster
> fix: label container images correctly

- .github/renovate.json
Leverage https://docs.renovatebot.com/modules/manager/#managers to group dep updates.
This will allow all base image SHA bumps to be grouped.
> chore: group deps by matchManagers

- README.md
We already have a clear section at top of README pointing out language connectors.
> chore: de-dup README section on connectors

- cmd/options.go
- cmd/options_test.go
- cmd/root.go
The internal users of the Go API prior to this commit had to mix Go
options with CLI string arguments to achieve the desired invocation
(e.g., WithLogger and "--max-connections"). This results in a brittle
API that is error prone.
This commit moves all the internally used options into the programmatic
API such that internal callers can invoke the Proxy without passing any
string based arguments.
> chore: expose additional CLI options in Go interface

- README.md
Looks like the automation did not work because we were behind a version (should have been 2.8.1 but was 2.8.0)
> chore: bump README versions

- .build/gcs_upload.yaml
- .github/workflows/codeql.yml
- .github/workflows/coverage.yaml
- .github/workflows/govulncheck.yaml
- .github/workflows/lint.yaml
- .github/workflows/tests.yaml
- .github/workflows/v1-periodic.yaml
- go.mod
- go.sum
This commit updates all CI builds to use Go 1.22 by default.
In addition, we change the Go version in go.mod. This means any builds of the Proxy must use Go 1.22. Since we don't ship a public API in Go effectively, this is a not a user facing change.
> chore: bump to Go 1.22

- README.md
- cmd/config_test.go
- cmd/root.go
- cmd/testdata/config-json.json
- cmd/testdata/config-toml.toml
- cmd/testdata/config-yaml.yaml
- cmd/testdata/config.json
- cmd/testdata/config.toml
- cmd/testdata/two-instances.toml
When specifying keys in the configuration file, one must use kebab case. This commit ensures the instance connection names also use kebab case and updates the README to accurately describe the feature.
When configuring the Proxy with a config file, one must use matching flag names and specify any instances with the special key instance-connection-name, or instance-connection-name-i, where i is the zero-based index of the instance.
Follow-on to #2106
> fix: use kebab case for config file consistently

- cmd/options.go
- internal/proxy/proxy_other.go
Add Option `WithDebugLogging` to allow users starting proxy with `NewCommand` to enable debug logging.
Improve debug logging for fuse path with additional debug log messages.
> chore: add WithDebugLogging Option

- Dockerfile.bullseye
- Dockerfile.buster
This is a port of https://github.com/GoogleCloudPlatform/cloud-sql-proxy/pull/2159 for the v1 branch.
> feat: use Google managed Debian containers

- Dockerfile.bullseye
- Dockerfile.buster
This is a port of https://github.com/GoogleCloudPlatform/alloydb-auth-proxy/pull/627
> fix: use public mirrors for base images

- README.md
We need to fix the automated release please version bump as it thinks the `--address` value of `0.0.0.0` is a version it should bump. Fix prior to next release to verify
> chore: update README `--address`

- internal/proxy/proxy_other.go
- internal/proxy/proxy_other_test.go
If the fuse server fails to mount, the call to Close should not panic. This commit ensures that no panic's happen if fuse isn't properly configured.
Fixes #2013
> fix: ensure proxy shutsdown cleanly on fuse error

- cmd/root.go
- internal/healthcheck/healthcheck.go
- internal/healthcheck/healthcheck_test.go
The readiness probe should not depend on downstream connections. Doing so can cause unwanted downtime. See [1]. This commit removes all dialing of downstream database servers as a result.
In addition, after the Proxy receives a SIGTERM or SIGINT, the readiness check will now report an unhealthy status to ensure it is removed from circulation before shutdown completes.
[1]: https://github.com/zegl/kube-score/blob/master/README_PROBES.md#readinessprobe
Fixes #2083
> fix: don't depend on downstream in readiness check

- cmd/root.go
Add additional debug log entries around `shutdownCh` to allow for verification that SIGINT/SIGTERM signals are being properly sent.
> chore: add debug logs around shutdownCh

- README.md
[CONTRIBUTING.md](https://github.com/GoogleCloudPlatform/cloud-sql-proxy/blob/939e21b035c41faa452a5737f83223bf8fcc7233/CONTRIBUTING.md) has no `contributor-code-of-conduct` header. 
I think [CODE_OF_CONDUCT.md](https://github.com/GoogleCloudPlatform/cloud-sql-proxy/blob/main/CODE_OF_CONDUCT.md) is the best destination for this link (that file was added by a google bot that didn't update the readme). It's also possible that this should link to the `review-our-community-guidelines` header in `CONTRIBUTING.md`. I'm happy to update this PR to do that if that's the case.
> docs: Fix link to code of conduct in readme

- README.md
Add rendered notices to README for better readability and to allow notices grab readers attention.
Example important notice: 
Example note notice
> chore: update README with rendered notices

- README.md
- cmd/root.go
- internal/proxy/proxy.go
In version 2.7.0, the `/quitquitquit` endpoint was updated to accept GET requests (in addition to POST requests, which it already accepted). See [changelog](https://github.com/GoogleCloudPlatform/cloud-sql-proxy/blob/main/CHANGELOG.md#270-2023-09-19). Also see the PR that made this change, https://github.com/GoogleCloudPlatform/cloud-sql-proxy/pull/1947.
Recently, while debugging a k8s shutdown problem, I quickly skimmed the readme to check that I was using `/quitquitquit` correctly and became convinced that I wasn't because I was sending a GET request. I had copied the example here, but didn't remember that in the moment:
https://github.com/GoogleCloudPlatform/cloud-sql-proxy/blob/848e1ea79287ac4772d603ff6391d0fcd8483cb5/examples/k8s-health-check/proxy_with_http_health_check.yaml#L107-L11 …
> docs: update documentation of accepted /quitquitquit HTTP methods

- internal/proxy/fuse_test.go
- internal/proxy/proxy_other.go
This change makes FUSE-configured connections behave the same way as normal connections: 
the proxy process should exit when there is an error accepting a connection while listening on 
the local server socket.
> fix: exit when FUSE errors on accept 

- cmd/root.go
- cmd/root_test.go
- internal/proxy/proxy.go
This makes the proxy continue to accept new connections for a period of time
after receiving the TERM signal.
Fixes #1640
> feat: Add parameter --min-sigterm-delay

- Dockerfile.bookworm
- README.md
Add support for Debian 12 `"bookworm"` and remove support for
Debian 10 `"buster"` as its LTS ended on June 30 ([debian wiki](https://wiki.debian.org/LTS)).
Using Debian build from Cloud Marketplace: [gcr.io/cloud-marketplace-containers/google/debian12](gcr.io/cloud-marketplace-containers/google/debian12)
This will require internal changes to our release script as well.
Fixes #2072
> feat: add support for Debian bookworm

- internal/proxy/fuse_test.go
- internal/proxy/proxy_other.go
Ignore context passed into `Lookup` as it can be cancelled by
interrupts in go-fuse. Instead create a new context when `Lookup`
is invoked.
Fixes #2260
> fix: ignore go-fuse ctx in Lookup

- README.md
Undoing the release-please changes that updated the `0.0.0.0` address to the Proxy version.
> chore: correct address in README

- internal/proxy/proxy_test.go
All of the tests in `proxy_test.go` use either port `50000` or `60000`. 
This has caused several flaky tests issues to arise with the error `listen tcp :50000: bind: address already in use`.
To mitigate this issue we can increment the ports in tests to all use unique ports. 
This will also allow isolating which tests are causing trouble based on the port.
Fixes #2166
> chore: update tests to use unique ports

- .github/workflows/tests.yaml
Currently the Proxy only has one tests suite that runs all tests.
Adding a unit tests suite that skips integration tests. 
This will allow for forked PRs to run only unit tests.
Related to #2282
> ci: add unit test build

- .github/workflows/tests.yaml
Pull request from forks once merged will still be skipped because `github.event.pull_request.head.repo.full_name` will still be that of the fork.
To combat this we run the job on all events that are not a pull_request (aka `schedule` and `push`)
> ci: skip integration tests on fork PRs

- README.md
Cloud SQL Proxy images were migrated to Artifact Registry from
Google Container Registry which is now deprecated.
Updating README to make this clear to users.
Closes #2211
> docs: clarify container images are stored in Artifact Registry

- .github/workflows/codeql.yml
- .github/workflows/coverage.yaml
- .github/workflows/govulncheck.yaml
- .github/workflows/lint.yaml
- .github/workflows/tests.yaml
- .github/workflows/v1-periodic.yaml
- go.mod
> feat: bump to Go 1.23

- cmd/cloud_sql_proxy/cloud_sql_proxy.go
On startup of v1 Proxy we will notify users of v2 and encourage migrating
to take advantage of new features and improvements.
> fix: add migration message on startup of v1 Proxy

- cmd/options.go
- cmd/root.go
- internal/healthcheck/healthcheck_test.go
- internal/proxy/fuse_test.go
- internal/proxy/proxy.go
- internal/proxy/proxy_other_test.go
- internal/proxy/proxy_test.go
Add a command option for adding a callback function for the connection refuse events due to max connection limit.
> feat: callback notify function when connection is refused

- cmd/options.go
- internal/healthcheck/healthcheck.go
Rename `max` vars. 
New `golangci-lint` check now does not allow variable names to be `max` or `min` due to built-ins.
> chore: don't overwrite builtin max function

- README.md
> docs: Describe environment variable configuration in the README.

- go.mod
- go.sum
Fuse dep was upgraded as part of https://github.com/GoogleCloudPlatform/cloud-sql-proxy/pull/2318 but is causing failures, downgrading.
Closes #2325 
Closes #2324 
Closes #2323 
Closes #2322
> chore: bump down go-fuse dep

- examples/k8s-sidecar/job_with_shutdown_hook.yaml
- examples/k8s-sidecar/proxy_with_sa_key.yaml
- examples/k8s-sidecar/proxy_with_workload_identity.yaml
Small updates to examples:
- Bumping k8s examples to latest proxy version `v2.14.1`.
- Enabling IAM AuthN by default in examples, this is what we showcase in our [samples repos](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/cloud-sql/postgres/sqlalchemy/deployment.yaml#L83) so aligning docs
- Lint YAML files
> chore: bump examples to latest Proxy and showcase IAM AuthN

- README.md
Adding notice to top of README about Cloud SQL Proxy connections
over unix sockets on MySQL 8.4 instances not being supported.
Related to #2317 
Related to #2359
> docs: add notice about MySQL 8.4 and caching sha2 plugin

- examples/k8s-health-check/README.md
- examples/k8s-health-check/proxy_with_http_health_check.yaml
- examples/k8s-service/README.md
- examples/k8s-service/pgbouncer_deployment.yaml
- examples/k8s-sidecar/README.md
- examples/k8s-sidecar/job_with_sidecar.yaml
- examples/k8s-sidecar/proxy_with_sa_key.yaml
- examples/k8s-sidecar/proxy_with_workload_identity.yaml
- examples/multi-container/ruby/README.md
- examples/multi-container/ruby/multicontainer.yaml
Running the proxy as a native sidecar container is now the preferred way to run the proxy. Using native
sidecars makes the lifecycle much easier to manage: 
- Kubernetes will start the proxy container and wait until it is ready before it starts the application container.
- Kubernetes will keep the proxy container running until the application container exits.
- Kubernetes will stop the proxy container after the application container exits. 
- The exit status of the proxy will not impact the pod's overall exit status.
This is especially important for Job and CronJob workloads. 
Native sidecar containers are supported by default in Kuberenetes 1.29.  See [K8s Sidecar Container](https://kubernetes.io/docs/concepts/workloads/pods/sidecar-containers/)
> docs: Update kubernetes examples to use K8s native sidecar containers.

- .github/workflows/coverage.yaml
- .github/workflows/lint.yaml
- .github/workflows/tests.yaml
- go.mod
Go 1.24 was released, see https://go.dev/doc/go1.24.
Related to #2387
> chore: update v1 Proxy to use Go 1.24

- README.md
In #2363 we added support to configure Proxy with a DNS domain name.
This PR adds docs explaining how to configure the Proxy with a DNS domain name.
---
The Proxy can be configured to use DNS to look up an instance. This would
allow you to configure your application to connect to a database instance, and
centrally configure which instance in your DNS zone.
Add a DNS TXT record for the Cloud SQL instance to a **private** DNS server
or a private Google Cloud DNS Zone used by your application.
**Note:** You are strongly discouraged from adding DNS records for your
Cloud SQL instances to a public DNS server. This would allow anyone on the
internet to discover the Cloud SQL instance name.
For example: suppose you wanted to use the domain name
`prod-db.mycompany.example.com` to connect to your …
> docs: add how to configure Proxy with DNS domain names

- cmd/root.go
- docs/cmd/cloud-sql-proxy_wait.md
Without --health-check or --prometheus, the server http does not start
> docs: update wait command help message

- .ci/cloudbuild.yaml
- .github/workflows/tests.yaml
- tests/mysql_test.go
Add integration tests for MySQL for Cloud SQL's [Managed Connection Pooling](https://cloud.google.com/sql/docs/mysql/managed-connection-pooling) (MCP)
Reference: https://github.com/GoogleCloudPlatform/cloud-sql-python-connector/pull/1267
> test: add MySQL MCP tests

- cmd/root.go
- docs/cmd/cloud-sql-proxy.md
- internal/proxy/proxy.go
- internal/proxy/proxy_test.go
- migration-guide.md
Port `skip-failed-instance-config` from v1 to v2. If set, this will ignore connection errors instead of exiting on startup. See more use case details in associated issue.
fixes https://github.com/GoogleCloudPlatform/cloud-sql-proxy/issues/2451
> feat: add flag for ignoring bad connections
