- README.md
cc @jeffmendoza
Jeff, I switched the exmaples to YAML. I couldn't get "kubectl create secret" to work though:
$ kubectl create secret generic foobar --from-file=README.md
Error: unknown flag: --from-file
I'm on kubectl 1.1.7, maybe that's the problem?
> Switch sample to YAML.

- README.md
It seems like this is required some of the time? I don't think it's responsible for #9, but it wouldn't hurt to try adding this.
> Add ssl certs volume.

- cmd/cloud_sql_proxy/cloud_sql_proxy.go
- cmd/cloud_sql_proxy/proxy.go
- proxy/fuse/fuse.go
- proxy/proxy/client.go
- proxy/proxy/common.go
Solving the first few points on https://github.com/GoogleCloudPlatform/cloudsql-proxy/issues/11
> Improve some logging

- cmd/cloud_sql_proxy/cloud_sql_proxy.go
- cmd/cloud_sql_proxy/proxy.go
- tests/gce_test.go
Currently just works for GCE and is relatively simple. Eventually I hope to add other platforms and check more functionality.
> Add integration test

- cmd/cloud_sql_proxy/cloud_sql_proxy.go
- proxy/certs/certs.go
- proxy/dialers/mysql/hook.go
- proxy/proxy/dial.go
- tests/dialers_test.go
- tests/gce_test.go
Add support for using the proxy as a library, exposing network-level and driver-level Dial funcs.
> Add dialer support

- cmd/cloud_sql_proxy/cloud_sql_proxy.go
- cmd/cloud_sql_proxy/proxy.go
- cmd/cloud_sql_proxy/proxy_test.go
Use .s.PGSQL.5432 as the socket filename
> Add support for Unix Socket connections to Postgres databases

- README.md
README: Kubernetes Secret configuration file should be name `secret.yaml` instead of `secret.json`
> README: Kubernetes Secret configuration file should be secret.yaml

- tests/gce_test.go
Often VMs cannot immediately be SSH'd to after creation. A retry fixes this, and we might as well do it in the test instead of forcing people to retry the test itself
> Retry the SSH in gce_test for up to 100 seconds.

- proxy/proxy/client.go
- proxy/proxy/client_test.go
Reverts GoogleCloudPlatform/cloudsql-proxy#142
Oops, I thought chowski had given an LGTM, but I misread.
> Revert "Automatically refresh SSL certs before they expire"

- proxy/proxy/client.go
- proxy/proxy/client_test.go
Fixing https://github.com/GoogleCloudPlatform/cloudsql-proxy/issues/94. Review done internally.
> refresh SSL certs early

- README.md
Add mention of the new -ip_address_types and -term_timeout flags so customers don't need to figure it out by reading the source code.
> Update README file with -ip_address_types and -term_timeout flags

- cmd/cloud_sql_proxy/cloud_sql_proxy.go
> Fix credential flow.

- proxy/certs/certs.go
> Update dialer default behavior to "PUBLIC, PRIVATE" instead of just "PUBLIC".

- README.md
> Update README with GCR locations.

- .github/blunderbuss.yml
Assign issues to @dmahugh and PRs to @kurtisvg.
> Update issue/pr assignments.

- .kokoro/go113/common.cfg
- .kokoro/go113/continuous.cfg
- .kokoro/go113/periodic.cfg
- .kokoro/go113/presubmit.cfg
- .kokoro/tests/run_tests.sh
- tests/common.go
- tests/connection_limit_test.go
- tests/dialers_test.go
- tests/gce_test.go
Enables some continuous testing to be run on the repo. 
- Fixes #272
> Enable continuous testing.

- Dockerfile
> Prepare for v1.18 release. 

- README.md
Documentation changes for #368
Documentation changes only.
- Fixes #368
> Added .Net Proxy to Third Party Section

- examples/kubernetes/README.md
> fix(examples/k8s): Use consistent secret keys

- examples/kubernetes/no_proxy_private_ip.yaml
> fix(examples): Remove sidecar from no-proxy example.

- .build/alpine.yaml
- .build/buster.yaml
- .build/default.yaml
Add Cloud Build configs for deploying container images.
> chore(release): Add Cloud Build configs for deploying container images.

- .kokoro/go114/macos/common.cfg
- .kokoro/go114/macos/continuous.cfg
- .kokoro/go114/macos/periodic.cfg
- .kokoro/go114/macos/presubmit.cfg
- .kokoro/tests/run_tests_macos.sh
- tests/postgres_test.go
> test(macos): Add macOS kokoro config

- .github/renovate.json
- .github/workflows/release-please.yaml
> chore: housekeeping on automation configs

- Dockerfile.alpine
- Dockerfile.buster
Adds the "fuse" package to the alpine and buster based container images. 
- Fixes #444
> feat(containers): Add fuse to alpine and buster images

- .build/gcs_upload.yaml
- .kokoro/release_artifacts.sh
Couple of minor changes to the release process.
> chore(release): Minor changes to release scripts

- .github/release-please.yaml
- .github/release-please.yml
- .github/workflows/release-please.yaml
Update release-please-action to only handle tagging step. The bot will handle creating the release PRs.
> chore: update release-please action

- CHANGELOG.md
> chore(changelog): Clarify release tag format

- .github/renovate.json
> chore(renovate): Disable master issue creation until fixed

- .github/release-please.yml
- .github/workflows/release-please.yaml
- .github/workflows/update-versions.yml
Updating to use Github action to handle both release PRs and tagging releases.
> chore: remove bot and use action for release-please

- proxy/fuse/fuse.go
Changes the unmount behavior to only trigger after the proxy has already failed to successfully mount. This prevents it from removing non-fuse mounts, and enabled the proxy to work from inside a docker container.
One specific note is that when running in a container, docker doesn't seem to be able to unmount the folder correctly. As far as I can tell this is something specific to docker. 
- Fixes #444
> fix(fuse): only attempt to unmount directory if error occurs during initial mount

- .github/workflows/release-please.yaml
- README.md
Please provide a detailed description on what changes your PR will have.
- Fixes #557
> chore: fix sidecar example documentation URL

- .kokoro/tests/run_tests_macos.sh
> chore(ci): Update brew cask install command to new API

- proxy/limits/limits.go
> fix: improve logging for file descriptor limits

- .kokoro/go116/linux/common.cfg
- .kokoro/go116/linux/continuous.cfg
- .kokoro/go116/linux/periodic.cfg
- .kokoro/go116/linux/presubmit.cfg
Add check to run integration tests in Go 1.16.
- Fixes #615
> chore: add checks for go1.16

- .build/gcs_upload.yaml
> chore: update Go version for compiling to 1.16

- examples/kubernetes/proxy_with_sa_key.yaml
Copy'n'paste fix in documentation.
> chore: fix region tag in k8s sample

- examples/kubernetes/README.md
> chore: update k8s readme to include workload identity for node pool

- proxy/proxy/client.go
- proxy/proxy/client_test.go
Prior to this commit, the client assumed all attempts to refresh a
certificate would succeeed and therefore panic when an attempt failed.
This commit ensures the client returns early when errors occur.
Fixes #745
> fix: return early when cert refresh fails

- README.md
- cmd/cloud_sql_proxy/cloud_sql_proxy.go
See https://unix.stackexchange.com/a/367012/26069 for details.
Fixes #747.
> chore: add note about maximum socket length

- proxy/fuse/fuse.go
- proxy/proxy/client.go
- proxy/proxy/common.go
> chore: remove dead code

- .build/gcs_upload.yaml
- cmd/cloud_sql_proxy/cloud_sql_proxy.go
> feat: stop building darwin 386 binaries

- cmd/cloud_sql_proxy/cloud_sql_proxy.go
- proxy/fuse/fuse.go
- proxy/proxy/client.go
- proxy/proxy/client_test.go
> fix: ensure proxy shuts down gracefully on SIGTERM

- README.md
> docs: add example for using a Socks5 proxy to README

- README.md
> chore: update README Go badge

- examples/k8s-health-check/proxy_with_http_health_check.yaml
Aligns gce-proxy version with suggestions made in https://github.com/GoogleCloudPlatform/cloudsql-proxy/pull/995
- _<none>_
> docs(k8s): Update image tag in health check example

- README.md
> docs: improve proxy docs (ALL_PROXY vs HTTPS_PROXY)

- cmd/cloud_sql_proxy/cloud_sql_proxy.go
> feat: allow multiple -instances flags

- examples/k8s-sidecar/proxy_with_workload_identity.yaml
Changes the comment to be more authoritative.
> chore(k8s): update comment on resources section

- README.md
> docs: add note about default container

- cmd/errors.go
- cmd/root.go
- cmd/root_test.go
- go.mod
- go.sum
- internal/proxy/proxy.go
- internal/proxy/proxy_test.go
Callers may now launch the proxy and override the default address on a
per-instance basis.
> feat: add support for "address" query parameter

- examples/k8s-sidecar/proxy_with_sa_key.yaml
- examples/k8s-sidecar/proxy_with_workload_identity.yaml
> docs: add note about redirecting logs to stdout

- .github/workflows/lint.yaml
- .github/workflows/tests.yaml
- tests/healthcheck_test.go
> chore(ci): use Github Actions for integration tests

- examples/k8s-sidecar/proxy_with_sa_key.yaml
Fix trivial typo in comment.
Not relevant, there are no code changes.
None
> chore(examples): fix typo

- .build/gcs_upload.yaml
- .build/release_artifacts.sh
- Dockerfile
- Dockerfile.alpine
- Dockerfile.buster
- cmd/root.go
The are updated to build the correct executable for the v2 proxy.
> chore: Update Dockerfiles and artifacts to build the v2 proxy

- migration-guide.md
Fix "Listen on all interfaces" snippet for v1
> docs: correct v1 snippet in migration guide

- .github/workflows/lint.yaml
Should attempt to remove label as first step so that label is removed even if later steps fail in lint.
> chore(ci): move label step in lint job

- .github/release-please.yml
All settings from main need to be explicitly applied to v1 branch.
> chore: fix release please config for v1 branch

- proxy/fuse/fuse.go
- proxy/fuse/fuse_freebsd.go
> fix: don't build fuse on freebsd

- README.md
> docs: fix repo name

- .build/bullseye.yaml
- .build/release_artifacts.sh
- .build/tag_latest.sh
- Dockerfile.bullseye
- README.md
> feat: add bullseye container image

- cmd/root.go
The quiet flag disables all but error logs.
Fixes #1452
> feat: add quiet flag

- .github/labels.yml
> chore: add k8s label

- README.md
> docs: fix Windows URLs

- migration-guide.md
> docs: add note about private IP to migration guide

- .build/gcs_upload.yaml
- .github/workflows/coverage.yaml
- .github/workflows/lint.yaml
- .github/workflows/tests.yaml
- go.mod
Add support for latest Go version
> feat: add support for Go 1.20

- examples/k8s-health-check/proxy_with_http_health_check.yaml
- examples/k8s-service/README.md
- examples/k8s-service/pgbouncer_deployment.yaml
- examples/k8s-sidecar/README.md
- examples/k8s-sidecar/proxy_with_sa_key.yaml
- examples/k8s-sidecar/proxy_with_workload_identity.yaml
Updates the docker image version in the kubernetes examples to use 2.0.0.
> doc: Update k8s examples to use latest docker image version.

- Dockerfile.alpine
- Dockerfile.bullseye
- Dockerfile.buster
> fix: build statically linked binaries

- examples/k8s-sidecar/README.md
Also updates example image tag to 2.1.0
> docs(k8s-sidecar): fix credentials file flag

- cmd/root.go
> fix: log info message for quitquitquit

- cmd/root_test.go
> chore: add timeout to channel and HTTP read

- migration-guide.md
> docs: add note about container image name change

- .github/renovate.json
> chore: fix renovate.json

- README.md
Update README to use latest version of Proxy
> chore: update README to latest proxy version

- examples/multi-container/ruby/README.md
> fix: correct indentation on README YAML

- .github/release-please.yml
v1 branch will have version.txt moved to proxy/util folder. Update the release_please.xml file with the new location.
> chore: update version.txt for v1 branch (#1836)

- proxy/util/cloudsqlutil.go
- proxy/util/cloudsqlutil_test.go
This change is a simple resolution to a build configuration error in google3.
Also, fix two docstring lints.
> chore: embed version in test too

- cmd/root.go
- cmd/root_linux_test.go
- cmd/root_test.go
- go.mod
- go.sum
> feat: Add support for systemd notify

- .github/workflows/tests.yaml
- .github/workflows/v1-periodic.yaml
Disabling flakybot as Pub/Sub topic for it has been deleted causing step to fail.
> ci: disable flakybot

- .github/workflows/tests.yaml
- .github/workflows/v1-periodic.yaml
Reverts GoogleCloudPlatform/cloud-sql-proxy#2017
> ci: re-enable flakybot

- cmd/root_test.go
> chore: add test case

- README.md
Use the correct block tags defined [here](https://github.com/googleapis/release-please/blob/main/docs/customizing.md#updating-arbitrary-files)
Fixes #2119
> chore: Update release-please block tags

- go.mod
- go.sum
> deps: upgrade protobuf to latest version

- cmd/root.go
Fixes #2145 
Draft PR https://github.com/GoogleCloudPlatform/cloud-sql-proxy/pull/2148 shows that this fix works.
> chore: Use inline annotation for release-please to update version

- README.md
Add a _Working with Docker and the Proxy_ section that explains how to use the proxy via Docker on a local machine, including some comments about permissions over the credentials file.
This PR closes #2129 and is related to #1124.
I'm open to any comments you might have, style or content-wise. Thanks for the opportunity to chime in!
> docs: Improve Docker section in README (#2129)

- README.md
Docker section of README is missing release-please automated version bumping.
> chore: update automation of Proxy version

- .github/release-please.yml
- examples/k8s-health-check/README.md
- examples/k8s-health-check/proxy_with_http_health_check.yaml
- examples/k8s-service/README.md
- examples/k8s-service/pgbouncer_deployment.yaml
- examples/k8s-sidecar/README.md
- examples/k8s-sidecar/job_with_shutdown_hook.yaml
- examples/k8s-sidecar/proxy_with_sa_key.yaml
- examples/k8s-sidecar/proxy_with_workload_identity.yaml
Bump examples to use latest proxy version.
> chore: bump proxy version in examples

- Dockerfile.bookworm
- README.md
Forgot to push a nit comment change to #2267 on the remote branch prior to merging.
> chore: update README

- .github/workflows/tests.yaml
Add integration test secrets for CAS supported instance.
> ci: add env variables for CAS tests

- cmd/root.go
- docs/cmd/cloud-sql-proxy.md
Update verbiage for `--universe-domain` flag description to better align with other libraries.
> chore: update flag description

- .github/workflows/codeql.yml
- .github/workflows/coverage.yaml
- .github/workflows/docs.yaml
- .github/workflows/govulncheck.yaml
- .github/workflows/lint.yaml
- .github/workflows/tests.yaml
- .github/workflows/v1-periodic.yaml
- go.mod
Go 1.24 was released, see https://go.dev/doc/go1.24.
Fixes #2387
> chore: update to Go 1.24

- build.sh
Copy the build.sh script to the v1 branch of the proxy.
> chore: add build.sh to proxy v1 branch
